spring:
  data:
    redis:
      database: 5
      host: 127.0.0.1
      port: 6379
      password: ''
  datasource:
    username: 'root'
    password: 'Seirei17610616169'
    url: jdbc:mysql://127.0.0.1:3306/ts?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true

ali:
  certified:
    access-key: '阿里KEY'
    secret-key: '阿里密钥'
  oss:
    endpoint: 'oss-accelerate.aliyuncs.com'
    bucket-name: 'XXX'
    domain: 'https://XXX.oss-accelerate.aliyuncs.com'

we-chat:
  host: https://api.weixin.qq.com
  app-id: 'wx445276b78ffc502f'
  secret: '9839910935fafb448aeec7a0f2635568'
  template-id: '微信通知模板id'

operation:
  energy:
    #  注册
    registered: 9999999
    # 广告赠送
    ad: 1
  #  管理员登录
  auth:
    account: '57584895@qq.com'
    password: 'Seirei17610616169'


chat:
  token: 'sk-nhBw0VbDTMqXXWqeaBesEbQiwHbmt3UCWBuL2uqOUJdIBgle'
  server: 'https://usa.blueshirtmap.com/v1'
  model-list:
    - model: 'gpt-4o-mini'
      name: 'gpt-4o-mini'
    - model: 'gpt-4o-2024-11-20'
      name: 'OA-4o'
    - model: 'DeepSeek-R1'
      name: 'DeepSeek-R1'
    - model: 'DeepSeek-V3'
      name: 'DeepSeek-V3'



drawing:
  #  comfy-ui 服务器地址
  server: http://127.0.0.1:8000
  # 允许同时处理的并发数
  concurrent: 1
  # 最大提交任务数量
  submit-task-max: 100


server:
  port: 9000
